name: RABKL Newsroom

on:
  schedule:
    - cron: "0 */4 * * *"   # every 4 hours
  workflow_dispatch:        # manual run button in Actions tab

permissions:
  contents: write

jobs:
  newsroom:
    runs-on: ubuntu-latest
    env:
      SLEEPER_LEAGUE_ID: "1228186433580171264"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run newsroom
        run: node scripts/newsroom.mjs

      - name: Commit & push (if changed)
        run: |
          git config user.name "rabkl-bot"
          git config user.email "bot@users.noreply.github.com"
          git add content public || true
          git diff --staged --quiet || git commit -m "news: auto-publish"
          git push

      - name: Trigger Vercel deploy
        run: |
          curl -s -X POST "$VERCEL_DEPLOY_HOOK" || true
